### ISSUE TITLE
Include ledmaps for 2D

### ISSUE THREAD

**Issue by dosipod** [MoonModules/WLED#1]
Hi , 
Some use custom maps a lot as a practical way of  customizing the effects on the fly  for custom fixtures like cubes , it is currently working fine  with WLED 0.14.0-mdev (build 2210201) when the matrix is set to 1D   but not when you setup the unit with 2D . In that case ledmaps are ignored . 

**Is your feature request related to a problem? Please describe.**
Low priority feature request as it seems little user base 

**Describe the solution you'd like**
Ledmaps are available with 2D 

**Describe alternatives you've considered**
na

**Additional context**

Thank you for your ideas for making WLED better!

**Comment by MoonModules** [comment]
You say it is working fine with WLED 0.14.0-mdev, I tried this:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/91013628/200853081-a9227cd0-a3db-4140-ad15-2fa88458fafb.png">

but got this:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/91013628/200852589-41d2c638-b5f4-4967-87e3-c570f31afd99.png">

Is this also the way you do it?

**Comment by MoonModules** [comment]
And this also not working for me: 

<img width="313" alt="image" src="https://user-images.githubusercontent.com/91013628/200858260-6b8b8cf5-50e0-43eb-ae5c-48b3ab36a137.png">

it can show the ledmap which has been set in the api, but changing it does nothing (old values still in the api), does it work for you?

**Comment by dosipod** [comment]
Yes ledmaps  works fine with 14.0-mdev (build 2210201)  when in 1D mode . But  adding "ledmap":1 manually or selecting from list do not have any effect with 2D  setup . 
We never go any error in our case when adding that to a preset , it is just ignored  .Might be you see some other errors . We have tested the same on two units with 16x16 and 8x24 and we seen the same behavior 
![image](https://user-images.githubusercontent.com/87589371/200964916-8ae13437-12a4-4177-bfc9-27a425229105.png)

**Comment by ewoudwijma** [comment]
Found the errors I got are a different use case, will submit an issue to WLED AC for that

**Comment by ewoudwijma** [comment]
And working on ledmaps step by step: first fixed some stuff in WLED MM and added a pull request to WLED AC: https://github.com/Aircoookie/WLED/pull/2885.

Also for me to learn ledmaps ;-)

**Comment by dosipod** [comment]
Sorry to copy and paste  but we sent that in discord , We are testing 0.14.0.3.0 ,in 1D the ledmaps are picked up and will apply correctly to a preset.
However selecting any other effects will reset to no ledmap and you have to save a preset for each effect with the ledmap   . Also still as before ledmaps are ignored in 2D

**Comment by ewoudwijma** [comment]
I left some wrong code. Just removed it in latest commit.

Can you test and let me know if okay, then I can close this issue

Yea yeah, ledmaps in 2D still ignored, will come ... some day ;-) (eta within a month)

**Comment by dosipod** [comment]
Using  0.14.0.4.2 (build 2211192)  selecting any other effects will no longer reset the ledmap so that part is solved .
For including 2D in ledmap , you may take your time  as there is no rush , would be nice if you have a discussion open for that on gh as this  post was meant as  an enhancement to include 2D  and might tell us if there is much interest or not

**Comment by ewoudwijma** [comment]
I personally think that it is core functionality and not logical to have it not working in 2D and think it is doable to take the segment to logical matrix mapping, 2D uses, and apply ledmap to it:

[2,1,0] and [1,0,2] = [1,2,0]

Does that make sense?

**Comment by dosipod** [comment]
Yeah agreed it is core functionality , one area is confusing to us is that 2D mapping is already used 
with  custom effects and hence we though that its already supported  . I am not really sure of the outcome 
with different fixture but we are hoping existing 2D effects would look better when correctly mapped.  

We just found out that gaps in ledmaps is possible with -1 which is an example of undocumented feature
which I hope would help in tweaking 2D effects  without the need to code new ones  for none standard fixtures.

**Comment by ewoudwijma** [comment]
@dosipod How is it used in custom effects then? It uses setPixelColor so it would go through the same logic …

**Comment by ewoudwijma** [comment]
@dosipod Is this change working as it should and can we close this issue and submit a pullrequest to add this to upstream?

**Comment by dosipod** [comment]
@ewoudwijma  
Hello , Yes ledmaps  are now available  with 2D  setup as requested . Attached is the small demo we did and you tested  .  You may close or keep for others to verify .
Due to exams period we were not able to  customize  2D effects  using ledmaps  to have **good  looking** outcome for none standard fixtures  such as  cubes  which is the real goal but that could be another topic along with rotated panels ,3d and few other items that we could discuss in another thread . Thank you 
![2D_MAP_14MM_11_21_2022](https://user-images.githubusercontent.com/87589371/204962485-c5d541d4-f75d-474a-9718-91e2621e0160.gif)

**Comment by ewoudwijma** [comment]
Closed as it is implemented in WLED MM
