### ISSUE TITLE
Wrong licence

### ISSUE THREAD

**Issue by netmindz** [MoonModules/WLED#123]
### What happened?

/settings/sec - about still shows MIT licence

### To Reproduce Bug

.

### Expected Behavior

MM should show GPL

### Install Method

From MoonModules Release Page

### What version/release of MM WLED?

.

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ewoudwijma** [comment]
Corrected in latest commit
