### ISSUE TITLE
2D can't be disabled if the custom effect mod is enabled

### ISSUE THREAD

**Issue by fonta** [MoonModules/WLED#13]
### What happened?

If you use -D DISABLE_2D in the build flags, it will fail compiiling the custom effect usermod.

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/6190791/213565617-3043cf33-35f4-4409-814d-4e67f1e8ced8.png">

### To Reproduce Bug

Add -D WLED_DISABLE_2D to common_mm -> build_flags_max.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/6190791/213566198-3637521f-b10c-4deb-95c8-bec1b8e1ab54.png">

### Expected Behavior

Succesful build when you disable 2d

### Install Method

Self-Compiled or other

### What version/release of MM WLED?

Latest commit

### Which microcontroller/board are you seeing the problem on?

ESP32

### Relevant log/trace output

```shell
Compiling .pio/build/esp32_4MB_max/src/usermod.cpp.o
Compiling .pio/build/esp32_4MB_max/src/usermods_list.cpp.o
Compiling .pio/build/esp32_4MB_max/src/util.cpp.o
Compiling .pio/build/esp32_4MB_max/src/wled.cpp.o
Compiling .pio/build/esp32_4MB_max/src/wled00.ino.cpp.o
In file included from wled00/../usermods/customeffects/usermod_v2_customeffects.h:14:0,
                 from wled00/usermods_list.cpp:189:
wled00/../usermods/customeffects/arti_wled.h: In member function 'float ARTI::arti_external_function(uint8_t, float, float, float, float, float)':
wled00/../usermods/customeffects/arti_wled.h:193:19: error: '__gnu_cxx::__alloc_traits<std::allocator<Segment> >::value_type {aka class Segment}' has no member named 'drawArc'
           SEGMENT.drawArc(par1, par2, par3, par4);
                   ^
wled00/../usermods/customeffects/arti_wled.h:195:19: error: '__gnu_cxx::__alloc_traits<std::allocator<Segment> >::value_type {aka class Segment}' has no member named 'drawArc'
           SEGMENT.drawArc(par1, par2, par3, par4, par5); //fillColor
                   ^
Compiling .pio/build/esp32_4MB_max/src/wled_eeprom.cpp.o
Retrieved `.pio/build/esp32_4MB_max/src/wled_math.cpp.o' from cache
*** [.pio/build/esp32_4MB_max/src/usermods_list.cpp.o] Error 1
Compiling .pio/build/esp32_4MB_max/src/wled_serial.cpp.o
========================================================================== [FAILED] Took 22.41 seconds ==========================================================================
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fonta** [comment]
At this moment build fails even if custom effect is disabled.

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/6190791/224419945-8fcd4000-393a-43aa-a992-eb4e23a2a984.png">

<img width="731" alt="image" src="https://user-images.githubusercontent.com/6190791/224420425-0641cd8f-5993-4a12-b794-47878e15745f.png">

**Comment by MoonModules** [comment]
Hi Fonta,

This has been solved.
Can you check and can we close this issue?

**Comment by fonta** [comment]
@MoonModules Indeed seems to be solved. Cheers.

In the meanwhile the environments for codm are preventing a succesful built. It doesn't like the .
Error: Invalid environment name 'codm-controller-0.6-rev2'. The name can contain alphanumeric, underscore, and hyphen characters (a-z, 0-9, -, _)
