### ISSUE TITLE
Sporadic reboots caused by WTD with hardware watchdog - WLEDMM_0.14.1-b32.40 esp8266_4MB_S, build 2406240

### ISSUE THREAD

**Issue by CLAM01** [MoonModules/WLED#150]
### What happened?

I have two D1 Mini ESP8266s each that are "WLEDMM_0.14.1-b32.40 esp8266_4MB_S, build 2406240".

57 LEDS with WS2815 (12V) are connected. I use a power adapter 12V / 2A and a Stepdown module "MP1584EN Mini Step Down" for max 3A.

It doesn't matter whether I receive and play effects via Audioreactive or whether I independently set the two WLEDs to "Solid".

A reboot always occurs after undefined times (5 minutes, 1hour oder 8 hour ...), but I can't yet determine where it comes from.

Cables are strictly separated between 12V, 5V and DIN, as well as relay output.

I measured the voltage, but it is stable at 5.1 volts during the failure.

All cables are firmly soldered, so I have ruled out a loose connection.

The free heap is constant between 18 and 19 kB.

Capacitor and 420 ohm resistor is also installed.

For comparison, I also have an ESP32 WROOM with the successor version WLEDMM_0.14.1-b32.41 operating as an audio reactive master. This one has no problems whatsoever.

I don't know what to do here and am looking for help.

### To Reproduce Bug

i dont know.

### Expected Behavior

Stable operation, just like when using an ESP32 WROOM

### Install Method

From MoonModules Release Page

### What version/release of MM WLED?

WLEDMM_0.14.1-b32.40 esp8266_4MB_S, build 2406240

### Which microcontroller/board are you seeing the problem on?

ESP8266

### Relevant log/trace output

Startsequenz monitored over Arduino IDE:
---WLED 0.14.1-b32.40 2406240 INIT---
 WLEDMM_0.14.1-b32.40 esp8266_4MB_S, build 2406240.

CPU:   ESP8266 (id 0x00739A9E), 160MHz.
CPU    Last Restart Reason = 6 -> External System
FLASH: 4MB, Mode 2, speed 40MHz;  chip ID = 0x00164068

Mounting FS ...
Mount FS succeeded.
done Mounting FS; 968 kB free.

Successfully inited strip 0 (len 57) with type 22 and pin 13 (itype 4)

Usermods setup ...

Ada

GPIO	| Assigned to		| Info
--------|-----------------------|------------
i/o   0|	  Button            	  
i/o   1|	  ./.  |              	  Serial TX
i/o   2|	  ./.  |             	  (onboard LED)
i/o   3|	  ./.  |            	  Serial RX
i/o   4|	  ./.  |           	  
i/o   5|	  ./.  |             	  
i/o  12|	  Relay  |           	  
i/o  13|	  LEDs (digital) |   	  
i/o  14|	  ./. |              	  
i/o  15|	  ./. |              	  
i/o  16|	  ./. |              	  
i/o  17|	  ./. |              	  analog-in (A0)

WLED initialization done.

Ada
Connecting to xxxxxx / ******************* ...
Connected! IP address: xxx.xxx.xxx.xxx
mDNS started: wled-slave-2.local

### Anything else?

Cabling image:
![IMG_20240731_234820](https://github.com/user-attachments/assets/4f5af803-6dfa-476d-bc93-752c205cf708)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment]
Hi, 

Your wiring looks reasonable to me, maybe @lost-hope could give you more recommendations.

It looks like you're using gpio13 as a LED pin. Unfortunately this pin does not support hardware acceleration but its driven by 'bit-banging'. Bit banging on 8266 can lead to spurious WDT resets. Could you try one of the recommended pins (see below) and check if the problem still persists?


> You can use any other pin, but it will use the bitbang method, which is not recommended for reliability. It is best to stick to GPIO 1, 2, and if need be, 3.

https://mm.kno.wled.ge/features/multi-strip/#esp8266

**Comment by CLAM01** [comment]
Thanks for the valuable information.

Yes, I used GPIO 13 because for some reason the WLED from Aircookie wouldn't come up (boot) at GPIO 2.

But now I have MoonModules because it also contains Audioreactive for the ESP8266. cool thing.

Yesterday I also changed the GPIO on one of the WLED lights from 13 to 2 and since then it has been stable without reboots.

The second is still on GPIO 13 and has sporadic reboots.

The soldering iron is already warm and I will also change it to GPIO 2 and watch everything again.

Doesn't it make sense at this point to point out in WLED SOftware (LED preferences) that this port may not be suitable?

**Comment by CLAM01** [comment]
another question.
It is normal that the relay takes off / on / off when i do a reboot over "info" tab or the watchdog rebbots the WLED?

**Comment by softhack007** [comment]
> another question. It is normal that the relay takes off / on / off when i do a reboot over "info" tab or the watchdog reboots the WLED?

Yes, that could be normal, depending on your relay being active-high or active-low. 
During restart, the relay pin is controlled by the bootloader. I'm not sure if good old 8266 does initialize pins at boot 🤷 might be normal to have some "clickering".

**Comment by softhack007** [comment]
this is a good overview of "special" pins (not WLED related):
https://espeasy.readthedocs.io/en/latest/Reference/GPIO.html#best-pins-to-use-on-esp8266

**Comment by CLAM01** [comment]
Ok, on ESP32 the relay does not off/on/off on boot.
I have try anoter GPIO for relay on esp8266, but noting changed.


I think this is triggered by WLED. If you reboot when the stripe is off, there will be no off / on / off with reboot. Only if WLED is switched on at the time when a reboot is taking place.

This off / on / off only occurs when a manual reboot is made via the “info” tab or you create a exeption with many http request so the ESP restarts.

I don't think it's the ESP's fault, but in my opinion it's not good for the LEDs and the Realy in the long run.

I think it's related to the setting "LED preferences -> Turn LEDs on after power up/reset:"
I deactivated this because I don't want the light to be on when a restart occurs.

I think with a reset the pins are switched off, WLED starts and switches on the GPIO until it calls up the setting to leave the LEDs switched off. Hence the clicking when it was on before.

**Comment by CLAM01** [comment]
OK, it's the same with the original WLED from Aircookie.
I read the same thing at Tasmota.
The original issue has been resolved here. I'll close the ticket at this point
