### ISSUE TITLE
Compile broken by ESPAsyncWebServer

### ISSUE THREAD

**Issue by NickDolfin** [MoonModules/WLED#166]
### What happened?

Someone changed something and now I cannot compile it anymore.
Something similar but different happend at the other WLED git.

### To Reproduce Bug

Install the contents of the zip file in a directory and start Visual Studio Code with platformio.
Open the folder and the problem appears as shown in the trace.

### Expected Behavior

I can compile an older Wled source that has not been changed.

### Install Method

Self-Compiled or other

### What version/release of MM WLED?

WLED-0.14.1-beta.32.zip

### Which microcontroller/board are you seeing the problem on?

ESP32-S3

### Relevant log/trace output

```shell
Resolving esp32s3dev_8MB dependencies...
Library Manager: Installing git+https://github.com/pbolduc/AsyncTCP.git @ 1.2.0
git version 2.46.0.windows.1
Cloning into 'C:\Users\nick\.platformio\.cache\tmp\pkg-installing-3smmwwej'...

Library Manager: AsyncTCP@1.2.0+sha.38b8475 has been installed!
Library Manager: Installing makuna/NeoPixelBus @ 2.7.5
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: NeoPixelBus@2.7.5 has been installed!
Library Manager: Resolving dependencies...
Library Manager: Installing fastled/FastLED @ 3.6.0
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: FastLED@3.6.0 has been installed!
Library Manager: Installing git+https://github.com/Aircoookie/ESPAsyncWebServer.git @ 2.2.1
git version 2.46.0.windows.1
Cloning into 'C:\Users\nick\.platformio\.cache\tmp\pkg-installing-ev8ptjds'...

PackageException: Package version 2.3.0+sha.00be156 doesn't satisfy requirements 2.2.1 based on PackageMetadata <type=library name=ESPAsyncWebServerWLED version=2.3.0+sha.00be156 spec={'owner': None, 'id': None, 'name': 'ESPAsyncWebServer', 'requirements': '2.2.1', 'uri': 'git+https://github.com/Aircoookie/ESPAsyncWebServer.git'}
```

### Anything else?

![Capture](https://github.com/user-attachments/assets/60a7b85e-36e8-46ec-8ba8-1f63b9de81c4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment]
hi @NickDolfin, this has happened over the weekend and affects all WLED forks.

I've just merged https://github.com/Aircoookie/WLED/pull/4142 which solves the problem.
