### ISSUE TITLE
Improve Peek/liveview2D

### ISSUE THREAD

**Issue by dosipod** [MoonModules/WLED#18]
![image](https://user-images.githubusercontent.com/87589371/218302552-de90ab8a-515f-4c92-b874-f969f9158ad2.png)
As you can see from the picture liveview2D is not as clear as peek . Might be tweak liveview2D to make clear  .
In those tests we used Firefox and Edge browsers and not really sure if browsers  setting could effect that but if so then that is good to share your own examples so we might be able to use as is .

Version tested is  WLEDMM 0.14.0-b1.18 (build 2302110)

Sorry for the mess ,we have few other suggestions related to peek and liveview2D , if you wish we can keep each in a separate requests as that could be easier to track or wait to make one big post .

**Comment by MoonModules** [comment]
Due to new setup of liveview2D black leds are not shown anymore

https://user-images.githubusercontent.com/91013628/228261252-1e91a515-be61-4743-b846-d5fa41d2fb7a.mov

@dosipod , is that what you hoped for ?
