### ISSUE TITLE
No longer able to save presets after factory reset 

### ISSUE THREAD

**Issue by dosipod** [MoonModules/WLED#2]
### What happened?

Very strange issue I hope someone could confirm  , when you flash to 0.14.0.3.0 (build 2211152) with OTA  presets will work but if you do a factory reset  then you  will no longer be able to save any presets unless you uncheck use current state . Also if you serial  flash  0.14.0.3.0 then you will not be able to save presets same as above and this  was observed with multiple units .   I am not sure if that issue was there in earlier versions and we missed that as last one we tested was 0.14.0.1.0
![image](https://user-images.githubusercontent.com/87589371/202059656-8890e780-14ba-4191-b6d5-f0aa1d7ebe1d.png)

### To Reproduce Bug

factory reset  and try to save presets 

### Expected Behavior

presets are saved 

### Install Method

Self-Compiled

### What version of WLED?

WLED 0.14.0.3.0 (build 2211152)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment]
Could be related to https://github.com/Aircoookie/WLED/issues/2886

**Comment by ewoudwijma** [comment]
That was already solved, this is related to this:

https://discord.com/channels/473448917040758787/779395228624617512/1043504303865856000

Just solved in latest WLEDSR commit.

Let me know if it works for you, then I can close this

**Comment by dosipod** [comment]
Tested in MM 0.14.0.4.2 (build 2211192)  and we can save presets after factory reset , you may close as you see fit
