### ISSUE TITLE
Can't find correct pinout for HUB75 in MoonModules v14.5.0-beta

### ISSUE THREAD

**Issue by ASMediaDev** [MoonModules/WLED#206]
### What happened?

I can't find correct pinout for HUB75 in MoonModules v14.5.0-beta.
In the log I can find that these pins are occupied by the HUB75 Interface:

![Screenshot 2024-12-19 at 22 54 01](https://github.com/user-attachments/assets/a0749792-6c89-4fca-9cbf-45015b25cf92)

But that doesn't not match up with any wiring configurations I can find for the esp32-S3

I noticed this build flag: "-D MOONHUB_S3_PINOUT ;; HUB75 pinout" but I can't find any corresponding pinout map named that way.

### To Reproduce Bug

ESP32-S3 16M Board with the corresponding build from VSCode

### Expected Behavior

The Matrix should be controllable but it doesn't even light up

### Install Method

Self-Compiled or other

### What version/release of MM WLED?

MoonModules v14.5.0-beta

### Which microcontroller/board are you seeing the problem on?

ESP32-S3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by softhack007** [comment]
> I noticed this build flag: "-D MOONHUB_S3_PINOUT

@ASMediaDev if you have a build with the "MoonHub" pinout, the mapping can be found here in the code

https://github.com/MoonModules/WLED/blob/fd2bce521b34b1b74853031dcd81d281b7dc167d/wled00/bus_manager.cpp#L748-L754

We did not find the time to document this, yet.

| HUB75  | ESP32S3 16MB |
|-----------|--------------|
| R1_PIN    | 1            |
| G1_PIN    | 5            |
| B1_PIN    | 6            |
| R2_PIN    | 7            |
| G2_PIN    | 13           |
| B2_PIN    | 9            |
| A_PIN     | 16           |
| B_PIN     | 48           |
| C_PIN     | 47           |
| D_PIN     | 21           |
| E_PIN     | 38           |
| LAT_PIN   | 8            |
| OE_PIN    | 4            |
| CLK_PIN   | 18           |

**Comment by ASMediaDev** [comment]
Thanks! Now it's working perfectly
