### ISSUE TITLE
2D effects shown despite only 1D strip configured

### ISSUE THREAD

**Issue by gradius-v** [MoonModules/WLED#27]
### What happened?

The effects list shows 2D effects, but only a 1D strip is configured.

### To Reproduce Bug

Configure a 1D strip.

### Expected Behavior

Only 1D effects are shown.

### Install Method

From https://wled-install.github.io/

### What version/release of MM WLED?

WLEDMM_0.14.0-b2.20_esp32_4MB_M.bin (build 2303260)

### Which microcontroller/board are you seeing the problem on?

ESP32

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dosipod** [comment]
Yes seems so . effects list shows 2D effects in 1D and they are on solid color without  animation . [edit same with AC main]

**Comment by MoonModules** [comment]
Agree with expected behaviour.

Can you test in latest AC main, I just did and also see 2D effects there in 1D setup... so something changed in AC main?

**Comment by MoonModules** [comment]
<img width="928" alt="image" src="https://user-images.githubusercontent.com/91013628/228181820-123ab2be-aa9c-48e5-8cfe-6e8591240ef0.png">

I suspect this code which has been recently updated in AC main for 0D support.

The remove('hide') in particular

@blazoncek, could that cause showing of 2D effects in 1D mode?

**Comment by dosipod** [comment]
Yes , updated to latest AC main and we see the same behavior.

**Comment by blazoncek** [comment]
Fixed locally.
Will be upstream after a while.
