### ISSUE TITLE
The 'MoonModules/WLED-Effects' repository doesn't contain the 'CustomEffects/wled' path in 'master'.

### ISSUE THREAD

**Issue by stiw47** [MoonModules/WLED#29]
### What happened?

Hi guys. First of all, big thanks for the great mod! I'm not sure should this be reported here or on [WLED-Effects](https://github.com/MoonModules/WLED-Effects) repo, but anyway....
On [WLED-Effects](https://github.com/MoonModules/WLED-Effects) repo, name of the folder was changed from CustomEffects to ARTIFX, so download of custom effects code from Custom Effects Editor is not working any more.

### To Reproduce Bug

In the MM WLED web UI, go to Segment, then to Custom Effects Editor and click on Download button - nothing will happen. I figured out what is going on when I clicked on Custom Effects Library button:

![image](https://user-images.githubusercontent.com/3337416/228922052-67a31101-6461-49c9-8290-6fa37dc0b680.png)

==>

![image](https://user-images.githubusercontent.com/3337416/228922197-654cd3d0-b303-49a1-ba61-1c5bb91c36a5.png)

==>

![image](https://user-images.githubusercontent.com/3337416/228922351-3a469772-41d0-44dc-8344-adf75014e243.png)

### Expected Behavior

As you guess, custom effect code should be downloaded.

### Install Method

From MoonModules Release Page

### What version/release of MM WLED?

 WLEDMM_0.14.0-b1.13_esp32_4MB_max.bin

### Which microcontroller/board are you seeing the problem on?

Other

### Relevant log/trace output

```shell
not relevant
```

### Anything else?

Thank you to the Moon and back for such a great fork!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ewoudwijma** [comment]
Thank you to the Moon and back for such a great fork! :-D 
You are welcome.

Just today we changed the name from custom effect to ARTI-FX to avoid confusion when people talk about custom effects and not talk about this.

If you use latest dev build of WLED MM (or also WLED SR) it will work again!

Can you find this build?

**Comment by stiw47** [comment]
I'm not sure, I downloaded always from [Releases](https://github.com/MoonModules/WLED/releases) page since now, last release is from December 2022 😁
If you could point me where from I could download it, I would be graceful. I believe you mean on daily builds? I read about that once on MM WLED wiki, but somehow I missed it out or didn't find it don't remember, most probably cause I was satisfied with release.

(To be honest, I'm using WLED last few years on several instances in my house. Until few weeks ago, I didn't knew that this MM fork exist and I was very happy when I discovered whole new world, but obviously didn't caught all important links yet)

Thx.

**Comment by lost-hope** [comment]
https://github.com/MoonModules/WLED/actions
click on the top most action and then scroll down to the artifacts. 
there are the default compiled enviroments

**Comment by stiw47** [comment]
Didn't knew for this, thanks a lot for the info, closing.

**Comment by ewoudwijma** [comment]
> top most action

Top most **mdev** action 👍
