### ISSUE TITLE
Analogue microphone audio reactivity not working with Lolin32lite

### ISSUE THREAD

**Issue by gaijinsr** [MoonModules/WLED#45]
### What happened?

Thanks for this great WLED branch, I really like all the extra functionality! I have an analogue microphone connected to VP/IO36 on my Lolin32lite. With the SR branch binary (soundReactive_WLED_0.13.3_ESP32.bin) audio reactivity works just as expected.
With MM, there is no audio reactivity. Although I have not modified the hardware setup at all, the system reacts as if no audio is received. I have set the analogue input to IO36, the digital microphone type to analogue and all the digital pins to n/a. I am using WLEDMM_0.14.0-b15.21_esp32_4MB_M.bin and everything else works as expected. Any ideas?

### To Reproduce Bug

Install WLEDMM_0.14.0-b15.21_esp32_4MB_M.bin on a Lolin32lite, connect an analogue microphone to VP/IO36. No sound reactivity (although the same setup works with SR 0.13.2).

### Expected Behavior

The system should react to sound.

### Install Method

From MoonModules Release Page

### What version/release of MM WLED?

WLEDMM_0.14.0-b15.21_esp32_4MB_M.bin

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

Thank you for your great work!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gaijinsr** [comment]
This still persists... Any idea, anybody?

**Comment by dosipod** [comment]
We have a lot of Lolin32lite MCUs used with analog mics ,analog line-in and even Bluetooth input  and they are working fine  using IO36 , go for latest build  but Lolin32lite  and wled are not guilty . You did not list the mic used which might be your issue . If you are using max4466 then that has been reported to  have issues , go for digital mic better or at least max9814 if you must use analog 

![image](https://github.com/MoonModules/WLED/assets/87589371/590e1b6b-27d1-4952-b364-6766a4df2cd7)

**Comment by softhack007** [comment]
This seems to be a hardware problem.
Lolin32lite seems to be an esp32, and in general analog input via gpio36 does work on esp32.
