### ISSUE TITLE
Setup https://moonmodules.github.io/WLED-Docs/

### ISSUE THREAD

**Issue by ewoudwijma** [MoonModules/WLED#6]
Created this issue to discuss how we should setup MoonModules documentation using https://moonmodules.github.io/WLED-Docs/ 

This is a fork of https://kno.wled.ge and is in initial setup.
- perfect symbiose of upstream info + fork info IMO.
- supported by GitHub workflows so any commit towards it will automatically update the pages.

See also https://github.com/atuline/WLED/issues/235

**Comment by ewoudwijma** [comment]
Current guidelines

- Welcome contains an extra paragraph on top called Welcome to WLED MoonModules, rest of the page is a 1:1 copy of upstream
- Basics, Features, Interfaces, Advanced, About is a 1:1 copy of upstream
- Added MoonModules, 2D and Sound Reactive
- MoonModules: features in WLEDMM not (yet) in upstream (except 2D and SR)
- 2D: 2D info
- Sound Reactive: SR info
- Some pages have been copy pasted from WLEDSR wiki, unmodified (e.g. Fork Comparison, 2D settings, SR settings, Digital Microphone Hookup), they need to be changed
- Every pages may contain a section at the bottom called Fork specific info (or similar) where differences compared to MM are described
- If a page has been moved from WLED SR Wiki to here, this WLED SR page can link to this.

Any comments?
What should be the menu structure/items? I know copied some of the wiki page titles of WLED SR, or should we introduce other page titles?

**Comment by dosipod** [comment]
Looks okay ,just small  comments , I do not think normal users will be interested to use MM much so you can skip the basic info that is already in the wled KB and focus on the more advanced functions  . Also as an example  I can not find reference to jmap in search

**Comment by ewoudwijma** [comment]
>skip the basic info that is already in the wled KB
* This is just a GitHub repo and a fork of kno.wled.ge so we get this info by default and will kept up to date if synced with upstream
* Unless decided otherwise, this work will not edit existing WLED AC pages but only add in the new Tabs
* The big advantage of this being a fork we have all info in one place

>as an example I can not find reference to jmap in search
* It's still WIP and I just added the map text here: https://moonmodules.github.io/WLED-Docs/moonmodules/mappings/ so now you can search on it, not a lot if info though  ;-)

**Comment by ewoudwijma** [comment]
To make the next step in improving this repo, I made a 1:1 copy of everything what is on the WLEDSR / Wiki page (and removed stuff from the 2D and Sound Reactive tabs).

<img width="750" alt="image" src="https://user-images.githubusercontent.com/1737159/207376375-9568b6e9-d4aa-4085-a4ef-cd1bf3cae521.png">

As a 'test' I added info similar as in WLED AC wiki on some of the current WLED SR Wiki pages as follows:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/1737159/207377144-12e376c8-98f7-491b-a3c0-db9fbe3e06e3.png">

I am not sure yet what to do with this. Should I add this to all pages?
@softhack007 what do you think as you are the main editor, what are the next steps for the WLEDSR wiki?

For  https://moonmodules.github.io/WLED-Docs/ I think the way forward is:
* Ask aircoookie how he plans to add 2D and SR info in kno.wled.ge (where in the menu hierarchy)
* Depending on his answer create the pages on the right page, if not sure yet we use the 2D and SR tabs to slowly migrate the content in WLEDSR to the 0.14 definitions
* We submit pull request on new 2D/SR documentation to upstream

**Comment by softhack007** [comment]
> I am not sure yet what to do with this. Should I add this to all pages?
> @softhack007 what do you think as you are the main editor, what are the next steps for the WLEDSR wiki?

Hi, currently I don't update the SR Wiki so often, but a few times already added some details after we had discussion on discord or on gh bugreports.

I think we should keep the wiki pages  where they are, and add something like you suggested - like "latest/updated info is available in wled-docs". Because some people learned how to find the wiki. Only problem was you cannot search it on google.

Seems I need to learn the new system ;-) Generally its ok for me to make new edits in wled-docs only.

Another small thing - we need to adjust the "help" links in SRWLED to point to the new locations.

**Comment by ewoudwijma** [comment]
Indeed maybe better 'leave it as is' and also keep the links in the app the same. Think it is better after some more thoughts. I removed the links from WLEDSR to WLEDMM Docs

Maybe our update procedure can be driven by questions on discord or on just what we think needs to be done:

1) question requires update / clarification in documentation
2) if SR impact then update WLEDSR/Wiki documentation
3) if 0.14 / MM impact then migrate info in WLEDMM/Docs from WLEDSR tab to the right place, so we slowly build our new documentation (MM specific to MoonModules tab and 0.14 general to 2D/SoundReactive tab)
