### ISSUE TITLE
Animartrix effects: weird colors in some effects

### ISSUE THREAD

**Issue by FragMenthor** [MoonModules/WLED#82]
### What happened?

Some effects give me colors that do not match the rest of the effect. Nomally is a solid green color that is superimposed on the effect, like some limit has been reached.
Namelly:
- Complex _Kaleido_3:
![image](https://github.com/MoonModules/WLED/assets/74264069/9c4b8ac5-7c00-4050-86ce-bdfd862c0803)
- Hot_Blob:
![image](https://github.com/MoonModules/WLED/assets/74264069/025b846f-2f40-4091-b6bb-bf8f5e7bdb1b)
- Lava_1:
![image](https://github.com/MoonModules/WLED/assets/74264069/88d383e6-a4d7-460e-ba0a-eb76c56aeac6)
- Module_Experiment_2:
![image](https://github.com/MoonModules/WLED/assets/74264069/d5da910b-faf1-4b66-bc03-2aba38cc3682)
- Module_Experiment_3:
![image](https://github.com/MoonModules/WLED/assets/74264069/ad091d55-06b8-4510-a355-943b3dcdb379)
- Module_Experiment_6:
![image](https://github.com/MoonModules/WLED/assets/74264069/2396882c-fe54-4869-a464-d9ada0525303)
- Module_Experiment_7:
![image](https://github.com/MoonModules/WLED/assets/74264069/738f8371-3a39-4a9c-9a8e-b2e2ed34e7a1)
- Module_Experiment_8:
![image](https://github.com/MoonModules/WLED/assets/74264069/596bad5a-d8fc-4ea0-a492-c8508d4ff471)
- Module_Experiment_9:
![image](https://github.com/MoonModules/WLED/assets/74264069/08d0b101-cef5-4049-b444-eec935a2c65d)
- Parametric_Water:
![image](https://github.com/MoonModules/WLED/assets/74264069/a3884c03-0c07-4bdf-9fdd-87693a97d91a)
- SM_10:
![image](https://github.com/MoonModules/WLED/assets/74264069/187815fb-b602-4d7e-b3f1-b85461dd4bc9)
- Water:
![image](https://github.com/MoonModules/WLED/assets/74264069/c573cebd-b20c-40dc-9251-ccace173e3cb)
- Zoom_2:
![image](https://github.com/MoonModules/WLED/assets/74264069/b2a038aa-18e0-4c4b-8045-5eae4d193969)

### To Reproduce Bug

Don't know if anyone more has this problem, but is shows for me in the UI and it reflects on the LEDs. This shows for me like this since the initial implementation of Animartrix in WLED, and no matter what version I use (_M _S, custom, ...) No change with any version, and I update almost weekly in my test setup with 'mdev'.

### Expected Behavior

Smooth and continuous effects, they change abruptly using solid colors, and seem broken somehow.

### Install Method

Self-Compiled or other

### What version/release of MM WLED?

WLEDMM_0.14.0-b27.32 esp32_4MB_M.bin
build 2310081

### Which microcontroller/board are you seeing the problem on?

ESP32

### Anything else?

 I don't think this is the expected normal behaviour. If this is intentional, the please close the issue. Thank you!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dosipod** [comment]
The weird colors has been noticed and reported since the initial implementation of Animartrix .as  palette is not used we thought that it is still WIP . You have described it better then we did

**Comment by FragMenthor** [comment]
What is the possibility of adding pallettes to these effects?

**Comment by dosipod** [comment]
@netmindz  could say as he is the one who ported the  Animartrix

**Comment by netmindz** [comment]
So it doesn't really make sense to use a palette due to the way the effects are designed so I don't see Stefan ever adding that to his code.

There are a few bugs where the colours don't reset properly when you move to certain effects.

Due to the lack of a gamma correction a few don't work in quite the same way as on Smart matrix.

As for blocks of colour with no fade, I've not seen this behaviour

**Comment by dosipod** [comment]
This FX192 Water example  , it is really very good as i  recall i seen it from Stefan , other then the strange superimposed  color which spoils it , thank you for the work though i do hope it could be improved even if as a future plan since you already did the hard part 
![192_water](https://github.com/MoonModules/WLED/assets/87589371/caa813fc-69c6-401d-9033-ad5beb67ae52)

**Comment by netmindz** [comment]
This fix should certainly help https://github.com/netmindz/animartrix/commit/8fd0df3e0b006244d53eaf480c2720daa5a697aa

Pulled in with https://github.com/MoonModules/WLED/pull/83

**Comment by dosipod** [comment]
I have tried to experiment  and change all the values under led preference ,Buffer , Gamma ,FPS ..etc but it is worth noting that the issue is not with all effects but only few of them ( e.g waves  seems perfect) ., the one listed by the OP is somewhat still the same , FX192 Water is also still the same .  
![192_water_v2](https://github.com/MoonModules/WLED/assets/87589371/bc67a9fe-72e8-4776-9939-683fef5cc976)

**Comment by netmindz** [comment]
Please test the patterns and report any bugs with them against

https://github.com/netmindz/animartrix/tree/OO

WLED just wraps this library. When I raised the issue of the colours of Water Stefan said it related to fact it was designed for SmartMatrix which has gamma correction

**Comment by netmindz** [comment]
Quick (untested) attempt at adding gamma correction https://github.com/MoonModules/WLED/pull/85

**Comment by netmindz** [comment]
Found what's wrong with water - the red is going negative and so flipping to full brightness

**Comment by netmindz** [comment]
Next daily build has fixed version of rgb_sanity_check

**Comment by netmindz** [comment]
Should all now be resolved I think @FragMenthor if you try this build https://github.com/MoonModules/WLED/actions/runs/6599717911 (scroll to the bottom for the assets)

**Comment by FragMenthor** [comment]
> Should all now be resolved I think @FragMenthor if you try this build https://github.com/MoonModules/WLED/actions/runs/6599717911 (scroll to the bottom for the assets)

Thanks!!! I will try tomorrow as soon as I can! 😀

**Comment by dosipod** [comment]
Yeah i have  tested all the effects and no more superimposed color so issue is fixed

**Comment by FragMenthor** [comment]
> > Should all now be resolved I think @FragMenthor if you try this build https://github.com/MoonModules/WLED/actions/runs/6599717911 (scroll to the bottom for the assets)
> 
> Thanks!!! I will try tomorrow as soon as I can! 😀



> Should all now be resolved I think @FragMenthor if you try this build https://github.com/MoonModules/WLED/actions/runs/6599717911 (scroll to the bottom for the assets)

Thank you! All effects seem OK now! Great job! 👍 💯
